### ISSUE TITLE
Plugin violates equals / hashCode contract for Value parameter

### ISSUE THREAD

**Issue by Kearny** [Haehnchen/idea-php-symfony2-plugin-doc#11]
Hi,

I have the following error showing up in InteliJ, sometimes completely freezes the entire app.

> Index fr.adrienbrault.idea.symfony2plugin.parameter2 violates equals / hashCode contract for Value parameter
> java.lang.Throwable
>   at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
>   at com.intellij.util.indexing.MapReduceIndex.a(MapReduceIndex.java:755)
>   at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:456)
>   at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1632)
>   at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1563)
>   at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:507)
>   at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1520)
>   at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1505)
>   at com.intellij.util.indexing.UnindexedFilesUpdater.a(UnindexedFilesUpdater.java:105)
>   at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.a(CacheUpdateRunner.java:219)
>   at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1064)
>   at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.a(CacheUpdateRunner.java:236)
>   at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
>   at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:472)
>   at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:421)
>   at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
>   at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
>   at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:232)
>   at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:332)
>   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>   at java.lang.Thread.run(Thread.java:745)

**Comment by fprochazka** [comment]
The newest phpstorm does this, `145.1503` works fine.

**Comment by fprochazka** [comment]
duplicate https://github.com/Haehnchen/idea-php-symfony2-plugin/issues/737

**Comment by Haehnchen** [comment]
done
