### ISSUE TITLE
He plugin is consuming all my CPU

### ISSUE THREAD

**Issue by luizgamabh** [Haehnchen/idea-php-symfony2-plugin-doc#14]
PHP Storm with enabled Symfony Plugin is consuming all my CPU in a Symfony 2 Project. Disabling the plugin PHPStorm uses just 4% of CPU i7 6th gen.

**Comment by juananrey** [comment]
+1, I think it could be a memory issue. I am currently working with mac OS Sierra and an i7 processor, but it used to happen as well with an i5 processor. It's a pity as this is a wonderful plugin :(

**Comment by jtreminio** [comment]
@Haehnchen CPU usage shoots up to 200% with this plugin installed.

I would absolutely not be as useful in SF2 without this plugin, it is the best thing ever, but the CPU usage really needs to be controlled
