### ISSUE TITLE
Plugin feature "Type Provider" broke .phpstorm.meta.php

### ISSUE THREAD

**Issue by syrm** [Haehnchen/idea-php-symfony2-plugin-doc#15]
When Symfony plugin is activated, and "Type Provider" option turned on or not, .phpstorm.meta.php in my project doesn't work anymore.

When i disable Symfony plugin, everything works fine.

**Comment by oxman** [comment]
Well its related to "PHPTypes Resolver".
When i uncheck all "PHPTypes Resolver" it works again.
