### ISSUE TITLE
Create service menu generates tabs for YAML (which is not allowed)

### ISSUE THREAD

**Issue by Arkemlar** [Haehnchen/idea-php-symfony2-plugin-doc#19]
I use ToClipboard button and baste bufer to services.yml:
![screenshot5](https://cloud.githubusercontent.com/assets/19671202/26041112/4430ff86-3933-11e7-968e-4bd60be8ab6a.png)
And it results in "A YAML file cannot contain tabs as indentation" exceptions. The tabs are generated by this feature.

**Comment by Haehnchen** [comment]
wrong repository, but also fixed
