### ISSUE TITLE
Template-Action-creation

### ISSUE THREAD

**Issue by ShadowSocratex** [Haehnchen/idea-php-symfony2-plugin-doc#23]
Hi.
Just a quick-fix-issue.
You probably mistook braces in "Action" regex detection, because when I try to create a .html template for @Template controller method it cuts off every char that belongs to "Action" before "Action".

For example:
testAction -> tes.html.twig (missing 't')
tesActionAction -> tes.html.twig (missing 'Action')
thisActionIsOkAction -> thisActionIsOk.html.twig

**Comment by ansien12** [comment]
Same problem here.
