### ISSUE TITLE
Incompatible with PHP Storm 2018.1 - Upstream Issue

### ISSUE THREAD

**Issue by lloy0076** [Haehnchen/idea-php-symfony2-plugin-doc#25]
FYI

https://github.com/Haehnchen/idea-php-annotation-plugin/issues/115

### PHP Storm Version

2018.1

```
PhpStorm 2018.1
Build #PS-181.4203.565, built on March 28, 2018
[removed - privacy]
JRE: 1.8.0_152-release-1136-b20 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

### Error

```
2018-04-03
6:51 AM	Plugin Error
Problems found loading plugins:
  Plugin "Symfony Plugin" was not loaded: required plugin "PHP Annotations" not installed.
  Disable Symfony Plugin
  Enable PHP Annotations
  Open plugin manager

The following plugins are incompatible with the current IDE build: PHP Annotations which also takes this plugin out of the picture.
```

**Comment by chamss19** [comment]
uninstall and reinstall the plugin works for me

**Comment by casperh1nl** [comment]
I uninstalled and re-installed the plugin and now sometimes the classes wont render on my main screen. 

1. Open controller
2. Open other controller
3. Open first controller again

And things go weird and i see the second controller. If i resize the code block it re-renders to an empty screen.

**Comment by MvanRietschoten** [comment]
You first have to reinstall php annotations.
When I had it at version 5.2.1 it didn't work. Then after reinstalling it had v5.3 (don't why it didn't update itself, as it always does).
After that I installed the symfony plugin and it worked.
Hope this helps someone.

**Comment by wmschram** [comment]
Updating both plugins also seems to do the trick. But @MvanRietschoten is right, thanks :+1:
