### ISSUE TITLE
Support Prefix imported route names.

### ISSUE THREAD

**Issue by leevigraham** [Haehnchen/idea-php-symfony2-plugin-doc#31]
It would be great if this plugin supported prefixes for imported route files.

![image](https://user-images.githubusercontent.com/25124/60311525-f1aa6480-999a-11e9-8a6d-5161163bd24f.png)

![image](https://user-images.githubusercontent.com/25124/60311564-1dc5e580-999b-11e9-9364-6aa4e7b9db7f.png)

![image](https://user-images.githubusercontent.com/25124/60311558-13a3e700-999b-11e9-9d7d-910b1e2dd6b0.png)

**Comment by lunetics** [comment]
That would be really great, also ran into the issue today

**Comment by oniice** [comment]
Would be good to see! Hopefully this could include the Laravel route name prefixes, which can get added in RouteServiceProvider with the `->as('name.prefix.')` option on routes

**Comment by vyk12** [comment]
Having the same issue, would be awesome to have :)

**Comment by apokalipscke** [comment]
Came here to report this too. Would be really nice if this gets fixed :D
