### ISSUE TITLE
Feature request: controller test template

### ISSUE THREAD

**Issue by MacDada** [Haehnchen/idea-php-symfony2-plugin-doc#5]
What?
http://symfony.com/doc/current/book/testing.html#your-first-functional-test

Where?
* Rightclick on editor with controller => Generate => Functional Test (with Symfony icon)
* Rightclick on folder => New => PHPUnit => Controller Functional Test (with Symfony icon)

**Comment by Haehnchen** [comment]
wrong repo ;)
