### ISSUE TITLE
Methods in controllers are no longer linked to the routes they belong to

### ISSUE THREAD

**Issue by CJDennis** [Haehnchen/idea-php-symfony2-plugin-doc#53]
The small Symfony icon is next to each method in my Controllers, and when I click on it, it shows me all sorts of related code, but it doesn't show the route anymore from `routing.yml`. I'm using PhpStorm 2021.1.4 and Symfony plugin 0.23.210. I'm not sure what version combination I was using when it last worked.

**Comment by CJDennis** [comment]
OK, so that's odd! I clicked on the "m" icon next the route in `routing.yml` and it took me to my method, and now all the routes are showing and are navigable! Is the plugin not finding `routing.yml` manually, but once it knows it's there it can link to it?

**Comment by Haehnchen** [comment]
the file needs to be inside the phpstorm index, if not its not found. for some reason your index was not updated
